import { getTranslations, unstable_setRequestLocale } from 'next-intl/server'
import { PropsWithChildren } from 'react'

import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'

import { locales } from '@/navigation'
import { getMetadata } from '@lib/metadata'

import Footer from '@ui/organisms/footer'
import Header from '@ui/organisms/header'
import Navbar, { NavProvider } from '@ui/organisms/navbar'
import { ThemeContextProvider } from '@ui/organisms/themeLayout'

type Props = PropsWithChildren & { params: { locale: string } }

export function generateStaticParams() {
  return locales.map(locale => ({ locale }))
}

export async function generateMetadata({ params: { locale } }: Props) {
  const t = await getTranslations({ locale })
  return getMetadata({
    title: t('title'),
    description: 'Generated by create next app'
  })
}

export default function RootLayout({ children, params: { locale } }: Props) {
  unstable_setRequestLocale(locale)
  return <ThemeContextProvider>
    <NavProvider>
      <html lang={locale} className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className="w-full h-full bg-stone-50 dark:bg-stone-950 text-black dark:text-white">
      <Header/>
      <main className="container grid grid-cols-[max-content,1fr]">
        <Navbar/>
        <div className="px-4 py-2.5">
          {children}
        </div>
      </main>
      <Footer/>
      </body>
      </html>
    </NavProvider>
  </ThemeContextProvider>
}